apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ilias.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ilias.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ilias.name" . }}
    spec:
      containers:
        - name: ilias
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          env:
            - name: ILIAS_DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: ILIAS_DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: ILIAS_DB_NAME
              value: {{ .Values.database.name | quote }}
            - name: ILIAS_DB_USER
              value: {{ .Values.database.user | quote }}
            - name: ILIAS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ilias.fullname" . }}-db
                  key: db-password
            - name: ILIAS_AUTO_SETUP
              value: {{ .Values.env.ILIAS_AUTO_SETUP | quote }}
            # add more as needed
          volumeMounts:
            - name: ilias-data
              mountPath: /var/iliasdata  # adjust to the correct path in the image
      volumes:
        - name: ilias-data
          persistentVolumeClaim:
            claimName: {{ include "ilias.fullname" . }}-pvc
